### ISSUE TITLE
Chin Sol equipped but no Close Range option in Configuration

### ISSUE THREAD

**Issue by lavaisreallyhot** [Openarl/PathOfBuilding#1354] opened 2019-01-03 07:32 UTC
I have Chin Sol equipped in items but there's no close range option in Configuration, nor is the 50% more damage being added to the DPS calc. Any idea what I'm doing wrong?

**Comment by moxaj** [comment] 2019-01-03 09:34
I've noticed other stuff missing as well, so I don't think the issue is specific to chin sol:
 - 'Do you have fortify?' missing
 - Rage input box and 'Have you killed recently?' missing with berserker ascendant

**Comment by moxaj** [comment] 2019-01-03 09:44
#1352 might also be related.

**Comment by Openarl** [comment] 2019-01-06 09:03
This has been fixed in a previous update.

**Closed by Openarl** 2019-01-06 09:03 UTC
