### ISSUE TITLE
[BUG] Can't get the main window active after the last 1.2.20 update

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#79] opened 2016-12-02 12:31 UTC
Dunno what have happened, just some magic is going on around.
So, I was working on a new build in 1.2.19, then pressed 'Update" button, everything went smooth. After I was done - pressed 'Save' and exited the program.
In a result of this chain: my build (that I was working on) not saved, the main window of PoB now stays on the background and I just can't set it active.
Any suggestions?
Also, have you implemented any kind of debug mode?
![](http://i.imgur.com/EzEgPWn.png)

**Comment by Openarl** [comment] 2016-12-02 12:43
Hmm. That's a new one. I haven't been able to reproduce it, so I have no idea what's going wrong. If you forcibly close the program and reopen it, does it work properly?

**Comment by dein0s** [comment] 2016-12-02 13:02
Nope, ain't working properly in any way.

**Comment by dein0s** [comment] 2016-12-02 13:06
Okay, managed to make it work after complete reinstall. But still...

**Comment by Openarl** [comment] 2016-12-02 13:09
Interesting. I wonder if you're experiencing the problem described in #30? The fact that it persisted until reinstall suggests that you might be.

**Comment by dein0s** [comment] 2016-12-02 13:12
Yep, same thing. Figured out, that something strange happened to Launch.cfg. Coords so far out of range..
``` set vid_last "1280,720,-32000,-32000,0" ```

**Comment by dein0s** [comment] 2016-12-02 13:14
I'll try to get some steps a bit later, gtg now.

**Comment by Openarl** [comment] 2016-12-02 13:45
Ahh I see. Well, if you can come up with a way of reliably reproducing the problem, it'd be a great help, as I had no luck diagnosing the cause when the issue was first reported.

**Comment by deadstarblues** [comment] 2016-12-02 14:58
I am experiencing the same issue and have the same extreme values in my launch.cfg:

`set vid_last "0,0,-32000,-32000,0"`

**Comment by Openarl** [comment] 2016-12-02 15:23
Well, I finally figured out the cause. The program's stored window position is only ever updated in response to a WM_MOVE message from Windows. It turns out that when a window is minimised, Windows sends a WM_MOVE message with the coordinates -32000, -32000; so if you minimise the program's window, then close it without restoring it, the saved position gets borked (and the size too, but that's less important). I'll add a check to prevent that from happening; the fix will be in the next update.

**Closed** 2016-12-02 15:35 UTC

**Comment by dein0s** [comment] 2016-12-02 15:39
Yep, I came up with the same conclusion.
Was just playing around with minimize and VMware Workstation (btw, PoB conflicts with it if app was launched before the virtual machine and machine launches in fullscreen - PoB just crash) to figure out the exact case.
Also, if two copies of PoB were opened and one of them was minimized (other stays in a normal state) problem occurs. Order of closing doesn't matter here (minimized first, normal first, close all at the same time).
