### ISSUE TITLE
3.0 suffix (chance to avoid being stunned)

### ISSUE THREAD

**Issue by Hapseleg** [Openarl/PathOfBuilding#462] opened 2017-07-24 09:20 UTC
Hi there, not sure if im just an idiot but it seems the slider for the suffix "chance to avoid being stunned" on shields is reversed? tier 4 is 20% and tier 1 is 13%? Surely higher percentage is better right?

Keep up the great work :) your program is such a great help and fun fooling around with

**Comment by Openarl** [comment] 2017-07-24 09:33
Modifiers are sorted into tiers based on their required level, but it seems that those modifiers haven't been given a required level yet; a lot of the new modifiers are missing data (such as the affix name), but it is still beta, so that's not surprising. This won't be fixed until GGG adds the required levels, as I can't easily edit the modifier data, since it's all exported from the game files. Anyway, the issue isn't with the program itself, so I will close this.

**Closed by Openarl** 2017-07-24 09:33 UTC
