### ISSUE TITLE
Notable "Gemini" does not grant accuracy when using two Piscator's Vigil Wands

### ISSUE THREAD

**Issue by N1gh7h4wk** [Openarl/PathOfBuilding#948] opened 2018-03-30 10:39 UTC
When using a different Wand + Piscator's Vigil it works, dualwielding two makes the node not work.

**Comment by Openarl** [comment] 2018-03-30 11:08
Could you give me your build? I can't manage to reproduce this; the node is correctly granting the bonus accuracy with two Piscator's equipped, and couldn't possibly fail to do so simply because of the specific wand you're using.

**Comment by N1gh7h4wk** [comment] 2018-04-04 10:45
Since i changed the build in the meantime, i tried to reproduce the issue but i did not succeed in doing so.

**Comment by Openarl** [comment] 2018-04-04 13:48
In that case I'll close this, as I cannot see how the described behaviour is possible.

**Closed by Openarl** 2018-04-04 13:48 UTC
