### ISSUE TITLE
Hits can't be evaded not computed correctly

### ISSUE THREAD

**Issue by dIggl3r** [Openarl/PathOfBuilding#573] opened 2017-08-18 00:25 UTC
I'm using The Temptestuous Steel sword, which has the implicit **Hit's can't be evaded**, yet in the dps window of PoB, Hit Chance isn't computing it.  Can we fix this please?

**Comment by dein0s** [comment] 2017-08-18 03:50
Working as intended for me: https://pastebin.com/JdW3T95Q

**Comment by dIggl3r** [comment] 2017-08-18 04:06
PoB shows mine having 89% hit chance, while in game it's 93%.  Bizarre?

**Comment by dein0s** [comment] 2017-08-18 13:24
Can you provide your build at least so we can figure out whats going on?

**Comment by dIggl3r** [comment] 2017-08-18 14:18
I switched builds and remapped my nodes... Next time *if* I see it, I'll come back and tell you.  :-/

**Comment by Openarl** [comment] 2017-08-21 11:40
It does seem to be working as intended, so I'll close this.

**Closed by Openarl** 2017-08-21 11:40 UTC
