### ISSUE TITLE
Commander of Darkness not correctly benefiting spell totem

### ISSUE THREAD

**Issue by Retik** [Openarl/PathOfBuilding#140] opened 2017-01-15 07:22 UTC
When using defensive auras with spell totem, the Commander of Darkness bonus gets applied twice, once to you and once to your spell totems. This causes double dipping of the CoD bonus that isn't being taken into account.

**Comment by Openarl** [comment] 2017-01-15 09:48
Are you sure that's meant to occur? As far as I'm aware, any kind of offensive bonus applied to a totem cannot affect the DPS dealt by it, since the DPS is only based on the player's stats. I'd need reliable proof to the contrary before I change it.

**Comment by Retik** [comment] 2017-01-15 10:58
Totems do get defensive auras, not offensive aura. The bonus provided by CoD is not an aura. 

The wiki states, "Auras and aura-like effects can affect totems (this includes degeneration effects),[1] summoned totems are only affected by auras that affect defensive properties, summoned totems still use their summoner's skills." 

Unfortunately I can't verify that this is working because the tooltip doesn't not register the totem's DPS, only mine. But it seems like it should be valid.

**Comment by Openarl** [comment] 2017-01-15 11:03
Whether it's an aura or not is irrelevant; if it's applying to the totem then it cannot possibly affect the DPS. That's just how totems work. And incidentally, CoD IS an aura, in the sense that it adds effects to your aura skills (which is why the bonuses are affected by aura effect passives, although the program doesn't currently factor that in).

**Comment by Openarl** [comment] 2017-01-20 04:38
Mark [has confirmed](https://www.reddit.com/r/pathofexile/comments/5oyzmg/commander_of_darkness_does_not_seems_to_give_cast/dcnrosx/) that CoD doesn't double dip, so I'm closing this.

**Closed by Openarl** 2017-01-20 04:38 UTC
