### ISSUE TITLE
[Feature Request] Mantra of Flames & Possibility to state the color of sockets

### ISSUE THREAD

**Issue by LordRegulus** [Openarl/PathOfBuilding#691] opened 2017-11-08 04:29 UTC
If you have mantra of flames equipped, it would be nice if in configuration you could have the options to say how many buffs are, so you can have an idea of your dsps if lets say you play with a support.

It would also be nice if you could choose the colors of the sockets for items like scaeva, prismatic eclipse or the new dialla's item.

Thanks again for everything Openal <3

**Comment by eps1lon** [comment] 2017-11-08 07:06
Duplicate of #648

**Comment by Openarl** [comment] 2017-12-24 11:38
#589 is now resolved; #648 remains but this duplicates it anyway so I will close this.

**Closed by Openarl** 2017-12-24 11:38 UTC
