### ISSUE TITLE
[BUG] Error while downloading update files

### ISSUE THREAD

**Issue by LaughedTheBoy** [Openarl/PathOfBuilding#70] opened 2016-12-01 23:25 UTC
Using the latest release version 1.2.0, when I open the program for the first time I get an error during the downloading of updated files:

![image](https://cloud.githubusercontent.com/assets/4335941/20816453/5182fc30-b7f0-11e6-8da2-8814dc497403.png)

Whenever it tries to update I get this same error, but it always fails after a random number of files are downloaded. Checking the Update folder in the tree, all files have been downloaded with the exception of the one that caused the error.

I'm using Win 10 64-bit

**Comment by Openarl** [comment] 2016-12-02 04:05
Hmm. There seems to be an issue with your internet connection, as the program is randomly encountering errors when connecting to the update server.

The program needs to update itself when run for the first time, as I only occasionally release new installer versions; I'm considering making that initial update optional with the next installer version, so that it will at least run the installed version. It won't entirely solve your issue though since you may have trouble updating it later.

**Comment by LaughedTheBoy** [comment] 2016-12-02 13:16
I don't think it's a problem with my internet connection as everything else internet related works fine (watching streams, online games, etc). Also, I'm able to import my POE character passive tree, skills, etc without issue.

I was looking through the code and noticed that you use curl 7.45 to download files. Would it be possible to update this to a newer version? Since the error occurs when curl is called to actually download the file, the only thing I could think was that maybe there is a problem with this libcurl dll version on Windows 10.

Thanks for the quick response and the excellent build tool.

**Comment by Openarl** [comment] 2016-12-02 13:30
I can certainly update libcurl (and probably a good idea anyway, as there'll be security updates), but I'd be surprised if that was the cause. Since it seems to be a random chance of any given connection attempt failing, I'll add a retry mechanism to the update downloading code, which should solve it regardless.

**Comment by kindasmitten** [comment] 2016-12-02 18:01
Not sure if this belongs in a new issue or not because I don't get this error when launching; I get it when checking for updates. Here's a snap of the error: http://puu.sh/sBTMm/6d8091a2f4.jpg

I can't say for certain that it's not my connection because I have been dealing with some connection issues today, but I've been messing with the program all day long and it has not once successfully updated. There are periods in which I know for a fact my connection is solid, everything outside of this program works fine, but it still gives the same error. 

Win10 x64, same as OP, and my version is stuck on 1.2.19

**Comment by Openarl** [comment] 2016-12-03 03:14
Well that's the same error code, and it occurs while updating, so it definitely belongs here. There's some changes in 1.2.21 that should help with this, but since the update system isn't working for you at all, you'll need to update the relevant file manually:
1) Download "UpdateCheck.lua" from [here](https://raw.githubusercontent.com/Openarl/PathOfBuilding/master/UpdateCheck.lua)
2) Locate the program's scripts folder. If you're using the standalone version, it's the folder you extracted the files to. If you used the installer, it's "%ProgramData%\Path of Building"
3) Overwrite the version of UpdateCheck.lua that's in that folder with the one you downloaded.
You don't need to restart the program if was running; you can do an update check right away and it'll use the new version.

**Comment by kindasmitten** [comment] 2016-12-03 05:21
That went smoothly, now at 1.2.21 and I know what to do if it happens again. Thanks for the help Openarl, wonderful program.

**Comment by Openarl** [comment] 2016-12-03 06:03
I'm glad to hear it's solved for you. I'll wait to hear from @LaughedTheBoy before I close this.

**Closed** 2016-12-21 10:38 UTC
