### ISSUE TITLE
Regression:  Gems no longer sorted by DPS

### ISSUE THREAD

**Issue by Asday** [Openarl/PathOfBuilding#1035] opened 2018-06-02 21:46 UTC
Previously, with a one skill added and selected as the main skill, adding another socket group would sort the gems by the DPS increase for the main skill, were they active.  For instance, if I had SRS as the main skill, a new socket group would have Anger sorted somewhere near the top, as it would grant a lot of DPS.

This is no longer the case.  plsfix <3

EDIT:  Correction - this is no longer the case as the "enabled" checkbox is unchecked by default on a new socket group for the first skill gem.  Ticking the box fixes the issue.  Is there a reason this default was changed?

**Comment by Openarl** [comment] 2018-06-03 02:02
I've already got a fix for this in the next update.

It actually wasn't caused by the "enabled" checkbox being unchecked, as that's always been the case, and has no direct effect on the DPS sorting. But it just happens that manually checking it acted as a workaround for the bug.

**Closed by Openarl** 2018-06-03 02:02 UTC
