### ISSUE TITLE
Fortify buff, unarmed crit chance

### ISSUE THREAD

**Issue by narkki** [Openarl/PathOfBuilding#254] opened 2017-03-22 02:35 UTC
Hi I can't seem to find fortify, is not in combat buffs. Also with rigwald's curse amulet equipped "critical strike chance with claws" does not increase unarmed crit chance like it should. Furthermore, the builder does not seem to take account the critical strike calculations "1+crit%" aka the "base crit" resulting in -100% crit chance in total (or the wiki is wrong). Thanks.

**Comment by Openarl** [comment] 2017-03-22 16:37
Fortify won't be listed in the combat buffs, as its effect isn't handled by the program yet. Conditions that depend on it can still work, but you may need to enable the Fortify option in the Configuration tab.

The modifier conversions on Rigwald's Curse aren't supported yet; as detailed in #207.

Could you clarify your statement about the base crit? I'm not aware of any issues there.

**Comment by narkki** [comment] 2017-03-22 18:41
Hi I'm talking about crit chance calculation since the program showed too
low in my opinion, when I do the math myself or check ingame (with weapon,
I don't have rigwald amulet yet) it shows more. I used this formula from
poewiki and it seems to work ingame.

http://pathofexile.gamepedia.com/Critical_strike

The base is 1 (100%) and if I manipulate item in PoB to have 100% more inc
crit the value looks correct. Am I wrong with this?


Narkki

On 22 Mar 2017 18:37, "Openarl" <notifications@github.com> wrote:

Fortify won't be listed in the combat buffs, as its effect isn't handled by
the program yet. Conditions that depend on it can still work, but you may
need to enable the Fortify option in the Configuration tab.

The modifier conversions on Rigwald's Curse aren't supported yet; as
detailed in #207 <https://github.com/Openarl/PathOfBuilding/issues/207>.

Could you clarify your statement about the base crit? I'm not aware of any
issues there.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Openarl/PathOfBuilding/issues/254#issuecomment-288459692>,
or mute the thread

**Comment by Openarl** [comment] 2017-03-23 02:01
If the crit chance of an attack appears to be too low, then that's almost certainly due to the [crit confirmation roll](http://pathofexile.gamepedia.com/Critical_strike#Accuracy); Path of Building factors that into the crit chance calculation, but the in-game tooltip does not.

**Comment by narkki** [comment] 2017-03-23 05:09
Oooooofc I'm stupid as ####. Thanks for reminding me.

**Comment by Openarl** [comment] 2017-03-23 05:14
All good, that catches a **lot** of people out. Since the remaining issue is a duplicate of #207, I'll close this now.

**Closed by Openarl** 2017-03-23 05:14 UTC
