### ISSUE TITLE
Spectral throw calculation

### ISSUE THREAD

**Issue by Kmanchine** [Openarl/PathOfBuilding#477] opened 2017-07-29 15:58 UTC
I do not get calculation on dps for spectral throw on latest version for 3.0. it works with other skills but not spectral

**Comment by Openarl** [comment] 2017-07-30 08:09
I can't find any issues with Spectral Throw. Are you sure you have a melee weapon equipped?

**Comment by Kmanchine** [comment] 2017-07-30 09:13
Sorry my mistake it was fixed, i had my weapons on second set so it was not calculating. but after adding it to first set it calculates, but when switching to second set it still does not calculate
![st1](https://user-images.githubusercontent.com/30554410/28752110-24c64cca-7518-11e7-861f-4ce3e3316144.PNG)
![st2](https://user-images.githubusercontent.com/30554410/28752109-24c2fcfa-7518-11e7-8af4-42c8faec988d.PNG)

**Comment by Openarl** [comment] 2017-07-30 09:52
Ok, now that isn't supposed to happen. I've tracked down the cause, so it will be fixed in the next update.

**Closed by Openarl** 2017-07-30 09:52 UTC
