### ISSUE TITLE
Shaper's Touch Gloves

### ISSUE THREAD

**Issue by sabromex** [Openarl/PathOfBuilding#32] opened 2016-10-08 11:27 UTC
When adding the unique Shaper's Touch Gloves, the stats do not calculate the physical damage increase.  http://pathofexile.gamepedia.com/Shaper%27s_Touch

**Comment by Openarl** [comment] 2016-10-08 11:32
Duplicate of #29

**Closed by Openarl** 2016-10-08 11:32 UTC
