### ISSUE TITLE
Oni Goroshi buff and some other funky bugs

### ISSUE THREAD

**Issue by MarsAndon** [Openarl/PathOfBuilding#831] opened 2018-02-09 23:55 UTC
Oni Goroshi - after ticking Her Blessing in config and removing the sword from character the buff stays on and its option disappears so you can't disable it until you put sword back on.

Shaper/elder items - sometimes the special mods get randomly added on other items. I've "crafted" an amulet with ele pen, for some reason that pen also got added onto my ring. It didn't appear in mods list and had to remove its line manually from text mods. Same happened with creating a chest and adding % inc max life on it, next belt I've crafted got that mod without me doing anything. Other than that some elder/shaper mods disappeared when I've tried to change mods on items, like after editing chest the % life disappeared. Update: Also can modify one of the regular mods while removing it from pre/suf dropdowns.
Other than that got some crashes on trying to edit influenced items but that was already reported.

**Comment by Openarl** [comment] 2018-02-21 03:35
All these should be fixed in the next update; the Oni-Goroshi, random adding of special mods, and the crash on editing are definitely fixed, and I can't reproduce the others on the latest dev version, so they may be fixed also.

**Closed by Openarl** 2018-02-21 03:35 UTC
