### ISSUE TITLE
PoB Client freeze after update

### ISSUE THREAD

**Issue by Vauxite** [Openarl/PathOfBuilding#450] opened 2017-07-12 19:24 UTC
Hello,

**Problem:**
The client becomes unresponsive/freezes when i try to launch it after an update. This happen every time there is an update.

**How to reproduce:**

1. Update Path Of Building
2. Close the client
3. Launch Path Of Building
4. Path Of Building is a white window (Not responding, using 10% cpu).

**Versions:**
Windows 10 Pro Version 1607 (14393.1358)
PoB VERSION[1.4.43][2017/07/06]

**Additional info:**
**CPU:** i7 6700k (tried both stock and OC)
**GPU:** GTX 970
**RAM:** 32GB ddr4
**Disk:** Intel 750 400GB
**In the textbox before the Not responding window**: https://pastebin.com/Uy8aVHCU

**Comment by Openarl** [comment] 2017-07-13 12:58
Is there any chance that you're actually experiencing #336? Because I can't think why relaunching after an update would trigger something like that.

**Comment by Vauxite** [comment] 2017-07-13 14:40
Thank you for replying.

I've looked at #336 and tried everything suggested. See below for result.

Not really sure what to make of this.
- **Spanning it across all 3 monitors.** - Works fine on next startup
- **Closing it on any monitor but primary** - Fails on next startup.
- **Closing it on primary**  - Works fine on next startup
- **Closing while stretched across at least 2 monitors** - Works fine on next startup

Where is start the exe file seems to play a role too. If I launch 'Path of Building.exe' from any monitor but primary it fails to launch (even with blank Launch.cfg).

Please let me know if you want any further tests.

**Comment by Openarl** [comment] 2017-07-13 14:51
Whaaaat? The monitor on which the .exe is opened actually makes a difference? Could you check if it's actually the monitor that the mouse cursor is on that is important? Because that at least makes some sense. If that's the case then I might have my first useful lead in this matter.

**Comment by Vauxite** [comment] 2017-07-13 14:59
The mouse location doesn't matter. However where the explorer.exe window containing "Path of Building.exe" matters only if the Launch.cfg is blank. I mean i can start the exe wherever as long as the PoB window touched my main monitor when closed.

To summarize, if Path of building tries to launch on any monitor but primary it fails.

**Comment by Openarl** [comment] 2017-07-13 15:03
That doesn't make any sense. By default, the program launches on the monitor that contains the mouse cursor, so it makes sense that if there's no saved window position then it can crash on startup. But the location of the explorer window shouldn't make the slightest bit of difference. Are you absolutely sure that's the case? You should be using the enter key to open the .exe while the cursor is on the primary monitor.

**Comment by Vauxite** [comment] 2017-07-13 15:10
You are correct. By using the enter key it will open the program on what ever monitor my mouse is on.
,

**Comment by Openarl** [comment] 2017-07-13 15:15
Ok. Well, this indicates that the problem isn't related to the code that restores the window position, since that doesn't run if Launch.cfg is empty.

What happens if you start the program with Launch.cfg containing nothing but the following line:
set vid_display 1

**Comment by Vauxite** [comment] 2017-07-13 15:21
The program launches on primary monitor.

**Monitor setup**
1 2* 3
*primary
1 & 3: AOC q2770Pqu
2: Acer XB271HU

If I close the program on 1 (rest of the values in Launch.cfg is unchanged):
`set vid_last "1280,720,-2272,383,0"`

on 2:
`set vid_last "1280,720,633,371,0"`

on 3:
`set vid_last "1280,720,2807,278,0"`

**Comment by Openarl** [comment] 2017-07-13 15:35
Hmm. I must admit, this hasn't gotten me quite as far as I'd hoped.

Could you try running the program with [this version](https://github.com/Openarl/PathOfBuilding/files/1145727/SimpleGraphic.zip) of SimpleGraphic.dll?

**Comment by Vauxite** [comment] 2017-07-13 15:42
No change. Only primary monitor works. 

By the looks of set vid_last, it seem that it treats all monitors as one wide monitor when referencing x_start and y_start.

**Comment by Openarl** [comment] 2017-07-13 15:44
What about the debug messages in the console window (the green text box)?

**Comment by Vauxite** [comment] 2017-07-13 15:49
The console window close shortly after and I'm greeted with a 1280x720px white window that doesn't respond.

http://imgur.com/a/ecmQ1

**Comment by Openarl** [comment] 2017-07-13 15:51
I need to see the contents of the console window with that new version of SimpleGraphic.dll in place; you're using the old one there.

**Comment by Vauxite** [comment] 2017-07-13 15:53
That's the one linked earlier.

**Comment by Novadesu** [comment] 2017-08-17 18:06
i have the same problem i want it fixed so bad..

**Comment by Openarl** [comment] 2017-09-24 07:12
I've added a response to #336 outlining a possible fix for this issue that will be coming in the next update. Regardless, this is a duplicate, so I will close this now.

**Closed by Openarl** 2017-09-24 07:12 UTC
