### ISSUE TITLE
3.0 Spectres missing

### ISSUE THREAD

**Issue by Megaddd** [Openarl/PathOfBuilding#747] opened 2017-12-13 12:08 UTC
Frost Sentinels, Solar Guards, etc. are currently not present in the Spectre Library.

Is this something that can be manually band-aided as a user, until they are implemented?

**Comment by marat569** [comment] 2017-12-18 14:19
Would love to see solar guards! (Take my energy)

**Comment by lyrjie** [comment] 2017-12-18 14:42
Duplicate of #492

**Comment by Openarl** [comment] 2017-12-18 23:55
Yeah, this is a duplicate.

I do really want to get these in, but unfortunately it isn't straightforward to do, as explained in the other issue.

**Closed by Openarl** 2017-12-18 23:55 UTC
