### ISSUE TITLE
Mod range issue

### ISSUE THREAD

**Issue by JYshadow** [Openarl/PathOfBuilding#354] opened 2017-05-22 13:04 UTC
The is something wrong with the `{range:}` code which causes the range of every mod being displayed in the `All items` tab, which basically only happens with rare and unique templates. This also causes the shared items tab to not save those mods properly. 
Also, could you perhaps add a search bar for the shared items tab?

**Comment by Openarl** [comment] 2017-05-22 13:35
There's actually two issues here:
1. The mod ranges showing in "All items" is caused by a mistake in the tooltip code for the "All items" control, which causing the items to display in "DB mode", which shows ranges instead of the current rolls. This bug was introduced in 1.4.11 when I overhauled the list controls; I'm surprised I haven't noticed it yet, although I have been focusing on other parts of the program since then.
2. The mod ranges not being saved when copying to the shared item list is caused by a flaw in the drag handler for the shared item list.

Both are fixed in the next update.

Adding a search bar for the shared item list is actually quite tricky since the item order is user-defined, unlike the unique/rare databases, which creates some odd issues if the list is being filtered in some way. That's why all lists in the program are either user sortable (skills, all/shared items, trees, spectres), or searchable/filterable (builds, unique/rare databases), but never both.

**Closed by Openarl** 2017-05-22 13:35 UTC
