### ISSUE TITLE
[Feature Request] Increase/Decrease per # of stats

### ISSUE THREAD

**Issue by misterch3n** [Openarl/PathOfBuilding#174] opened 2017-02-20 03:11 UTC
Hey guys just wanted to start off by saying PathOfBuilding has been a godsend and this program has the potential to be the best program for every player who doesn't have his/her own private excel spreadsheets.  I was wondering if it was possible to implement a feature similar to something found in D3Planner (Diablo 3's equivalent of a polished path of building for those unfamiliar): a quick reference table for increase/decrease in DPS per a certain stat such as 1% crit chance or 10 main stat.  Here is what it looks like on D3planner http://imgur.com/nl7tyVe .  Newer players like myself would find this quick, and for the most part accurate, comparison really useful to learn how to find upgrades for a character.  With the current PathOfBuilding I do this by creating a a few copies of my character ring and adding one different affix to each one, a very tedious process in my opinion when it doesn't have to be.

**Comment by snuze** [comment] 2017-02-22 15:10
Dupe of https://github.com/Openarl/PathOfBuilding/issues/146

However, good write-up & screenshot.

**Comment by Openarl** [comment] 2017-02-22 15:34
Yeah, I'll count this as a duplicate, since #146 covers this, and more.  
I should really make my thoughts known on this one... I'll post in #146, since that's staying open.

**Closed by Openarl** 2017-02-22 15:34 UTC
